### ISSUE TITLE
Parameter file fortran error

### ISSUE THREAD

**Issue by jpsal** [ftherrien/p2ptrans#16]
Hi, thanks for developing this software!
I have an issue if I want to run p2pint with an parameter file (it works properly without parameter file).
I created a file called p2p.in and copied the Fortran code from https://p2ptrans.readthedocs.io/en/latest/p2pint.html
When I then want to run p2pint, I get the following error: 

At line 2317 of file source/transform.f90 (unit = 11, file = './p2p.in')
Fortran runtime error: Cannot match namelist object name tol*1.0d-3tol_class

Thanks and best regards

**Comment by ftherrien** [comment]
Hi @jpsal,

Thanks for creating this issue. The problem was with the documentation: it indicated the default values, but they are not always valid entries for the parameter file (namelist). I updated the documentation so that you can copy the example directly.

By the way, you can put only the parameters that you want to change in the input file, you don't need to put all of them. For example, if you only want to change the bond length to 1.8 Angstrom, you can use:

```
&input2d
param = 1.8
/

```
I hope this helps!
