### ISSUE TITLE
Reading of parameter file

### ISSUE THREAD

**Issue by SimonMel** [ftherrien/p2ptrans#20]
First of all, thanks a lot for this amazing code!

I keep having troubles with adjusting the extra parameters. I am re-performing the FCC-BCC example using the standard p2p.in input file given in the documentation, but it keeps giving "Cannot match namelist object name ...". This is independent of the parameters included in the input file. 

My output is the following:
The optimization will be performed in the reversed direction.
Transition is *optimized* from BCC structure (POSCAR_BCC) to FCC structure (POSCAR_FCC)
Initial spacegroup in optimization: Im-3m (229)
Final spacegroup in optimization: Fm-3m (225)
Number of BCC structure (POSCAR_BCC) cells in sphere: 300
Number of FCC structure (POSCAR_FCC) cells in sphere: 300
Total number of atoms in each sphere: 300

Optimizing... (this may take several hours)
Check progress in ./progress.txt
Mapping time: 36.93604016304016
Trying to find periodicity directly (find_cell):
At line 2044 of file source/transform.f90 (unit = 11, file = './p2p.in')
Fortran runtime error: Cannot match namelist object name init_class

Previously, I also had the error message "Fortran runtime error: End of file" with the transform.f90 fortran file. Therefore, I tried to manually control the parameters by changing the default values written in this file. I think this should work as well, but is it normal that the sentence "WARNING: tmat changed by more then the set tolerence 1.000000e-05." in the output file will always give the same tolerance value of 1e-5?

Best regards

**Comment by ftherrien** [comment]
Hi @SimonMel,

Thanks for creating the issue! 

I think I know what the problem was. I made some changes, so let me know it that solved your problem. If not, could you send me what `p2p.in` file you are using exactly and what command you are using to call p2ptrans to get:

1.  `Fortran runtime error: Cannot match namelist object name init_class`
2.  `Fortran runtime error: End of file`
3. `WARNING: tmat changed by more then the set tolerence 1.000000e-05." in the output file will always give the same tolerance value of 1e-5`

If you get the warning (3.) you can often safely ignore it. But if you want to change the tolerence you will need to change it in the file  `p2ptrans/config.py` where p2ptrans is installed on your computer (e.g. `~/.local/lib/python3.9/site-packages/p2ptrans/config.py`) not in `p2p.in`.

**Comment by SimonMel** [comment]
Hi Félix,

Thank you very much, it work fine now! I was mainly asking because of the other error message: "WARNING: The number of classes found during the optimization is not sufficient to describe the transformation; increase the classification tolerence (tol_class)". However, changing tol_class will not change this, the error message remains to exist. 

I am mainly asking because of the following situation. I have been doing some tests (I can also provide you the POSCAR files), and found out that changing the tolerances has little effect. Nonetheless, changing the number of cells being tiled, does matter a lot. Although it doesn't really affect the quantitative aspects, nl. bain strains and transformation matrices, it does affect the spacegroups along the transition path. In some cases, it gave a low-symmetry path, i.e. spacegroups along the path were P1, C1, etc. while for some choices of -n I do find the high symmetry spacegroups along the transition path. I also verified the POSCAR in TransPOSCARS with phonopy to see whether the wrong intermediate POSCARS were used. I did this with phonopy with different tolerance parameter in searching for symmetry, but this was not the case.

Do you have any idea on what might be the cause of either finding a low or high symmetric transition path? Let me know if you would like to have the POSCARs to verify this.

Thank you a lot!
Best regards,
Simon

**Comment by ftherrien** [comment]
Hi @SimonMel,

Glad it solved the issue. 

The warning about the number of classes is also mostly harmless and does not matter much since version 2.0 (the classes are not really used anymore to find periodicity).

Yes `-n` is the most important factor in p2ptrans. With lower `-n` you should get simpler "Bain like" transformations with higher symmetry. With higher `-n` you should get more complex transformations with lower symmetry. You can read some of the implications of that in [this paper](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.125502).

Please feel free to email me if you have more questions. My first and last name at gmail.com.
