### ISSUE TITLE
p2p.in not found

### ISSUE THREAD

**Issue by dskoda** [ftherrien/p2ptrans#3]
Hi Félix,

I could not find the file p2p.in supplying the parameters for the run. Do you have an example of such a file?

https://github.com/ftherrien/p2ptrans/blob/0bcbd7162634f38f7ad51481bc75ac7d86511b70/p2ptrans.py#L35

Thank you very much!

**Comment by ftherrien** [comment]
Hi Daniel,

Thank you for signaling this issue! p2p.in is a namelist, you can create it as such (given that you are in the same directory as p2ptrans.py):

echo -e "&input\n/" > p2p.in

This is will use the default parameters. 

I will update the code so that it does not fail when the file is missing. In the coming weeks, I will also update the readme with much more information and examples!

Please feel free to ask if you have other questions!

**Comment by ftherrien** [comment]
This issue is fixed by commit 115a52ebd803d43337a10d0c2bf39215c326ee38

**Comment by dskoda** [comment]
Hi Félix,

It's working now. Thank you very much for your support!
Looking forward to seeing the new examples!
