### ISSUE TITLE
p2p.in missing 2

### ISSUE THREAD

**Issue by Ash-Pera** [ftherrien/p2ptrans#5]
Hi Félix,
Some later change seems to have broken the p2p.in fix and made it required again.

**Comment by Ash-Pera** [comment]
With most recent version (as of 15:30 Jan 30, 2020):
```
 ________    _______  ________
|\   __  \  /  ___  \|\   __  \
\ \  \|\  \/__/|_/  /\ \  \|\  \
 \ \   ____\__|//  / /\ \   ____\
  \ \  \___|   /  /_/__\ \  \___|
   \ \__\     |\________\ \__\
    \|__|      \|_______|\|__|

__________TRANSFORMATIONS__________

Traceback (most recent call last):
  File "p2ptrans.py", line 1291, in <module>
    with open(filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './p2p.in'
```

**Comment by ftherrien** [comment]
@Ash-Pera,

Yes I see, this is indeed a new issue...(The code now copies ths namelist file so you can see what paramater you used when you originally ran the code). It will be fixed in the next commit which will be sometime tonight. For now you can just put an empty file there: "touch p2p.in".

Thank you for raising this issue! I really appreciate it!
